apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:release
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2283
          envFrom:
            - configMapRef:
                name: immich-env
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-db-credentials
                  key: DB_PASSWORD
          volumeMounts:
            - name: upload
              mountPath: /usr/src/app/upload
      volumes:
        - name: upload
          persistentVolumeClaim:
            claimName: immich-upload
