apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-upload
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 50Gi
