apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6
  storage:
    size: 10Gi
    storageClass: local-storage
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-cnpg-secret
